### ISSUE TITLE
Agent DVR stops and restarts over and over (CentOS 8 Stream)

### ISSUE THREAD

**Issue by MVerBerkmoes** [ispysoftware/agent-install-scripts#20]
Clean install but Agent DVR stops, but restarts over and over.

Ran ./start_agent.sh at the CLI:

Starting...
Using default media location
Creating temp path for opencv in /tmp/
Get com port list
Using default port (8090)
Local Server running on port 8090
H264 compatible version of ffmpeg is required to use H264 encoding. Switch to VP8 in settings if unable to record.
Accepting http connections at http://*:8090/
Access locally at http://192.168.1.100:8090
Agent (v4.0.4.0)
Log start
Process is 64 bit
Using WorkStation GC
Init Webrtc
Init FFmpeg
Looking for ffmpeg in /usr/local/lib
Not in there..
Looking for ffmpeg in system default
ffmpeg path:
Initializing devices
vdpau
cuda
vaapi
qsv
drm
opencl
Found 0 devices
call arecord -l
Error: CMD: CMD: No such file or directory
ZeroConf: ZeroConf Service Started
Error: CMD:    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redi                                                                 rectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int3                                                                 2& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CoreLogic.Utilities.CMD.GetOutput(String exe, String strCommand)
No such file or directory
Error: No audio devices found
Error: Cuda Check: Cuda Check: The type initializer for 'Emgu.CV.Cuda.CudaInvoke' threw an exception.
Error: Cuda Check:    at Emgu.CV.Cuda.CudaInvoke.get_HasCuda()
   at CoreLogic.Threads.StartUp()
Error: Cuda Check: Cuda Check: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
Error: Cuda Check:    at Emgu.CV.CvInvoke.CheckLibraryLoaded()
   at Emgu.CV.Cuda.CudaInvoke..cctor()
Error: Cuda Check: Cuda Check: Unable to load shared library 'dl' or one of its dependencies. In order to help diagnose loading problem                                                                 s, consider setting the LD_DEBUG environment variable: libdl: cannot open shared object file: No such file or directory
Error: Cuda Check:    at Emgu.Util.Toolbox.Dlopen(String dllname, Int32 mode)
   at Emgu.Util.Toolbox.LoadLibrary(String dllname)
   at Emgu.CV.CvInvoke.LoadUnmanagedModules(String loadDirectory, String[] unmanagedModules)
   at Emgu.CV.CvInvoke.DefaultLoadUnmanagedModules(String[] modules)
   at Emgu.CV.CvInvoke..cctor()
Unable to load shared library 'dl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBU                                                                 G environment variable: libdl: cannot open shared object file: No such file or directory
Error: Load OpenCV: To debug this check the userguide at https://www.ispyconnect.com/userguide-agent-dvr.aspx#troubleshooting
Turn Server accepting connections at 192.168.1.100:3478 using range 50000-50010)
Preloading Images
Unhandled exception. System.TypeInitializationException: The type initializer for 'Emgu.CV.MatInvoke' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'dl' or one of its dependencies. In order to help diagnose loading pro                                                                 blems, consider setting the LD_DEBUG environment variable: libdl: cannot open shared object file: No such file or directory
   at Emgu.Util.Toolbox.Dlopen(String dllname, Int32 mode)
   at Emgu.Util.Toolbox.LoadLibrary(String dllname)
   at Emgu.CV.CvInvoke.LoadUnmanagedModules(String loadDirectory, String[] unmanagedModules)
   at Emgu.CV.CvInvoke.DefaultLoadUnmanagedModules(String[] modules)
   at Emgu.CV.CvInvoke..cctor()
   --- End of inner exception stack trace ---
   at Emgu.CV.CvInvoke.CheckLibraryLoaded()
   at Emgu.CV.MatInvoke..cctor()
   --- End of inner exception stack trace ---
   at Emgu.CV.MatInvoke.cveMatCreate()
   at CoreLogic.Utilities.Imaging.LoadStaticImages()
   at CoreLogic.Threads.StartUp()
   at AgentCore.Code.Initialize.Go()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
./start_agent.sh: line 11:  4897 Aborted                 (core dumped) dotnet AgentDVR/Agent.dll

**Comment by ispysoftware** [comment]
https://www.ispyconnect.com/userguide-agent-DVR.aspx#troubleshooting
