### ISSUE TITLE
Not possible to use local camera

### ISSUE THREAD

**Issue by 000xxx** [ispysoftware/agent-install-scripts#35]
**Describe the bug**
`ffplay` is not present.
Not possible to use local camera.

**Information**
```
zero@000pi:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
zero@000pi:~$ uname -a
Linux 000pi 5.15.0-1023-raspi #25-Ubuntu SMP PREEMPT Fri Jan 6 17:33:55 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

**Console output from installer**
```
<html><body>
<!--StartFragment-->

07:41:34 | Reconnect: Living room 1 - kitchen: Reconnecting in 5s
-- | --
07:41:37 | Found 14 devices
07:41:37 | List Devices: /dev/video23
07:41:37 | call ffplay -nodisp -f v4l2 -list_formats all /dev/video23
07:41:37 | CMD:  CMD: An error occurred trying to start process 'ffplay' with working  directory '/home/zero/AgentDVR'. No such file or directory
07:41:37 | Error:  CMD: CMD: An error occurred trying to start process 'ffplay' with  working directory '/home/zero/AgentDVR'. No such file or directory
07:41:37 | CMD:     at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo ,  String , String[] , String[] , String , Boolean , UInt32 , UInt32 ,  UInt32[] , Int32& , Int32& , Int32& , Boolean , Boolean )    at System.Diagnostics.Process.StartCore(ProcessStartInfo )    at CoreLogic.Utilities.CMD.GetOutput(String exe, String strCommand)
07:41:37 | Error:  CMD:    at  System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo , String ,  String[] , String[] , String , Boolean , UInt32 , UInt32 , UInt32[] ,  Int32& , Int32& , Int32& , Boolean , Boolean )    at System.Diagnostics.Process.StartCore(ProcessStartInfo )    at CoreLogic.Utilities.CMD.GetOutput(String exe, String strCommand)
07:41:37 | An error occurred trying to start process 'ffplay' with working directory '/home/zero/AgentDVR'. No such file or directory

<!--EndFragment-->
</body>
</html>
```

```
zero@000pi:~/AgentDVR$ sudo find / -name ffplay
zero@000pi:~/AgentDVR$
```

**Comment by ispysoftware** [comment]
dependance on ffplay was removed in the latest update, not sure if it made it to the docker version yet

**Comment by 000xxx** [comment]
OK, great, how to use local camera on Raspberry PI in this case?

**Comment by ispysoftware** [comment]
you'd need to update it - possibly i haven't pushed it live yet, got a large list of updates coming

**Comment by 000xxx** [comment]
Sorry for misunderstanding. Update what? I am using last version of script.

**Comment by ispysoftware** [comment]
I need to push an update. I'm currently testing it.

**Comment by 000xxx** [comment]
Latest version (commit 6a2a21b) did not solve issue unfortunately. Latest version of Agent still do not have `ffplay`.

**Comment by ispysoftware** [comment]
There is now no reference to ffplay in the codebase. It's calling ffmpeg instead

**Comment by 000xxx** [comment]
OK, great.

Camera is connected:

```
$ vcgencmd get_camera
supported=1 detected=1
```


Agent logs when I am tryinmg to refresh:
```
20:22:06 | Found 14 devices
-- | --
20:22:06 | List Devices: /dev/video23
20:22:06 | call ffmpeg-v5/workspace/bin/ffmpeg -f v4l2 -list_formats all -i /dev/video23
20:22:06 | List Devices: /dev/video31
20:22:06 | call ffmpeg-v5/workspace/bin/ffmpeg -f v4l2 -list_formats all -i /dev/video31
20:22:06 | List Devices: /dev/video22
20:22:06 | call ffmpeg-v5/workspace/bin/ffmpeg -f v4l2 -list_formats all -i /dev/video22
20:22:06 | List Devices: /dev/video21
20:22:06 | call ffmpeg-v5/workspace/bin/ffmpeg -f v4l2 -list_formats all -i /dev/video21
20:22:06 | List Devices: /dev/video20
20:22:06 | call ffmpeg-v5/workspace/bin/ffmpeg -f v4l2 -list_formats all -i /dev/video20
20:22:06 | List Devices: /dev/video16
20:22:06 | call ffmpeg-v5/workspace/bin/ffmpeg -f v4l2 -list_formats all -i /dev/video16
20:22:06 | List Devices: /dev/video15
20:22:06 | call ffmpeg-v5/workspace/bin/ffmpeg -f v4l2 -list_formats all -i /dev/video15
20:22:06 | List Devices: /dev/video14
20:22:06 | call ffmpeg-v5/workspace/bin/ffmpeg -f v4l2 -list_formats all -i /dev/video14
20:22:06 | List Devices: /dev/video0
20:22:06 | call ffmpeg-v5/workspace/bin/ffmpeg -f v4l2 -list_formats all -i /dev/video0
20:22:06 | List Devices: /dev/video13
20:22:06 | call ffmpeg-v5/workspace/bin/ffmpeg -f v4l2 -list_formats all -i /dev/video13
20:22:06 | List Devices: /dev/video18
20:22:06 | call ffmpeg-v5/workspace/bin/ffmpeg -f v4l2 -list_formats all -i /dev/video18
20:22:06 | List Devices: /dev/video12
20:22:06 | call ffmpeg-v5/workspace/bin/ffmpeg -f v4l2 -list_formats all -i /dev/video12
20:22:06 | List Devices: /dev/video11
20:22:06 | call ffmpeg-v5/workspace/bin/ffmpeg -f v4l2 -list_formats all -i /dev/video11
20:22:06 | List Devices: /dev/video10
20:22:06 | call ffmpeg-v5/workspace/bin/ffmpeg -f v4l2 -list_formats all -i /dev/video10
20:22:06 | call arecord -l
```


But unfortunately Agent cannot use:

![image](https://user-images.githubusercontent.com/35876933/220192547-92c3d473-3410-4cf3-a2b5-6dc735f8d828.png)


And also from Agent logs:

```
20:26:02 | Enable: Living room 1 - kitchen: Enabled
-- | --
20:26:02 | Living room 1 - kitchen:Reader: Living room 1 - kitchen: Cannot find device: /dev/video0
20:26:02 | Error: Living room 1 - kitchen:Reader: Living room 1 - kitchen: Cannot find device: /dev/video0
20:26:02 | SourceError: Living room 1 - kitchen: CoreLogic.Sources.Combined.MediaStream:Invalid Source (/dev/video0)
20:26:02 | Error: SourceError: Living room 1 - kitchen: CoreLogic.Sources.Combined.MediaStream:Invalid Source (/dev/video0)
20:26:02 | SourcePlayingFinished: Living room 1 - kitchen: Playing finished (DeviceLost)
20:26:02 | Reconnect: Living room 1 - kitchen: Reconnecting in 2s

```

**Comment by ispysoftware** [comment]
it's parsing the output from ffmpeg - if ffmpeg can't see your device then
Agent won't be able to either.
Possibly you need a version of ffmpeg with local device access enabled?

**Comment by 000xxx** [comment]
I have found solution:
```
echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/ffmpeg.libs.conf
sudo ldconfig
```
